### PR TITLE
Update run.sh to pass bash args to docker-compose for flexibility

### PR DESCRIPTION
**Pull request by chafreaky**

### CODE REVIEW

**Comment by maebeam** [comment]
I don't want to force this default on all users. Can you just pass all run.sh args to docker-compose instead?

**Comment by chafreaky** [comment]
Sure I'll update that

**Comment by chafreaky** [comment]
@maebeam I can open up a separate PR to update the readme or leave as is for now.

**Comment by maebeam** [comment]
feel free to update the readme in this pr

**Pull request merged**
